orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration 

version: 2.1 # using 2.1 provides access to orbs and other features

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 13.14.0
      - node/test:
          version: 12.18.2
      - node/test:
          version: 11.15.0
      - node/test:
          version: 10.21.0
